appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c3107603aeb3c0700447a41
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: Uf9XWD0RJ8Q27TWDrrmWFzp+jfk9gwVJFirr6X7Z54TYW6XRc9ODl7R5FZ29Qgu8cy8hBA+20eCN9nv0bIU1hooRnvEo5c2zFBtBY4B4xPJqRU4N6VqT4BMyo9RYZNMMsbEG1rCn+gstauOL+sta9YGGEQYEzYD+BtwdcVcvG8p0FXkga7fsPj7qMtLm/rXL4J3MGyJy39G7epz4x1vDKt0OvXKU6SN9R9X6GfLY55UaNsvabtkLiGFky8/3LnQELX4E6W3PSA+xFHPmu8e/EPZOJjyLSaS3QVNDtl8A0UzZo0wnGdcu+IWlwtD4sIlKw21j1AGtDgjstNep8UwO32GPJjWbwnxEpZxGT6CM6ZG144vBIDt+h4DD0IlCV6KY3YMfrYcVKvU4h4ZeGYDcMXFM2WXUA+/hdPLAE+Zqmfq0E3ubTAy0fk+u4xKlfcDYfy6QsP2hCtsjoBHrm6VsTlK32nI+Trb8CfYHDiVlCDHb15+/axNJ7CZTIabm7Iq+tCS8TKMn/L4K+W2F2vp0gN/uTcFgYIGlVQEiPqxT3fUJOVXgj69BPW90qCb2F0gM7tEOB/z4IJx4YHp7i7lkrig5u/W1968A/NjSPdq5VeYI8Zzpoh4R88CyC0pLZMN1MhWi5CzrX29xCuPN3kco7qXJ4CPX9YVHeMgnBa6wVZs=}
